fix: path public/style.css and add style.css.map

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -53,8 +53,8 @@ jobs:
         run: |
           git config --global user.name "github-actions[bot]"
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
-          git add style.css
-          git diff --staged --quiet || (git commit -m "Auto-generate style.css from updated SASS files" && git push origin main)
+          git add public/style.css public/style.css.map || echo "style.css or style.css.map not found, skipping commit."
+          git diff --staged --quiet || (git commit -m "Auto-generate style.css and style.css.map from updated SASS files" && git push origin main)
 
       - name: Configure AWS CLI
         run: |
